#!/bin/sh


# Set CPU characteristic
echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor


# Run Xorg
su root -l -c "/usr/bin/Xorg" &


# Set Volume
alsactl init
amixer sset 'PCM' 100%
amixer sset 'Headphone' 100%


# Set Time
#date -s '2020-01-04 11:56:30'  # set system clock
#hwclock -w -f /dev/rtc1    #  system clock -> hardware
hwclock -s -f /dev/rtc1     #  hardware -> system clock


# Enable CAN0
ip link set can0 type can bitrate 500000
ip link set can0 up
