NVIDIA_TEGRASTATS_VERSION_MAJOR = 21
NVIDIA_TEGRASTATS_VERSION_MINOR = 5.0
NVIDIA_TEGRASTATS_VERSION = $(NVIDIA_TEGRASTATS_VERSION_MAJOR).$(NVIDIA_TEGRASTATS_VERSION_MINOR)
NVIDIA_TEGRASTATS_SOURCE = Tegra124_Linux_R$(NVIDIA_TEGRASTATS_VERSION)_armhf.tbz2
NVIDIA_TEGRASTATS_SITE = http://developer.download.nvidia.com/embedded/L4T/r$(NVIDIA_TEGRASTATS_VERSION_MAJOR)_Release_v$(NVIDIA_TEGRASTATS_VERSION_MINOR)
NVIDIA_TEGRASTATS_LICENSE = custom
NVIDIA_TEGRASTATS_LICENSE_FILES = Linux_for_Tegra/nv_tegra/LICENSE
NVIDIA_TEGRASTATS_STRIP_COMPONENTS = 2

NVIDIA_TEGRASTATS_INNER_SRC     = Linux_for_Tegra/nv_tegra/nv_tools.tbz2
NVIDIA_TEGRASTATS_OUTER_SRC_EXTRACT_EXTRA = $(NVIDIA_TEGRASTATS_LICENSE_FILES)

define NVIDIA_TEGRASTATS_INSTALL_TARGET_CMDS
	$(INSTALL) -D $(@D)/tegrastats $(TARGET_DIR)/usr/bin/tegrastats
endef

$(eval $(prebuilt-nested-package))
